export interface Order {
  total: number;
  perPage: number;
  page: number;
  data: {
    date: string;
    user: string;
    orders: {
      orderId: string;
      orders: {
        id: string;
        createdAt: string;
        updatedAt: string;
        orderId: string;
        amount: number;
        user: {
          id: string;
          firstName: string;
          lastName: string;
        };
        items: {
          id: string;
          createdAt: string;
          updatedAt: string;
          quantity: number;
          price: number;
        }[];
      }[];
    }[];
  }[];
}

// Generated by https://quicktype.io

export interface IOrders {
  total: number;
  perPage: number;
  page: number;
  data: {
    date: string;
    items: {
      id: string;
      amount: number;
      createdAt: string;
      user: string;
      orderId: string;
      orders: {
        id: string;
        createdAt: string;
        updatedAt: string;
        quantity: number;
        price: number;
      }[];
    }[];
  }[];
}
