// Generated by https://quicktype.io

export interface IOrders {
  total: number;
  perPage: number;
  page: number;
  data: {
    date: string;
    items: {
      id: string;
      amount: number;
      createdAt: string;
      user: string;
      orderId: string;
      orders: {
        id: string;
        createdAt: string;
        updatedAt: string;
        quantity: number;
        price: number;
      }[];
    }[];
  }[];
}

// Generated by https://quicktype.io

export interface Order {
  id: string;
  createdAt: string;
  updatedAt: string;
  orderId: string;
  amount: number;
  user: {
    id: string;
    firstName: string;
    lastName: string;
    phoneNumber: string;
    email: string;
    image: {
      id: string;
      public_id: string;
      secure_url: string;
    } | null;
  };
  items: {
    id: string;
    quantity: number;
    price: number;
    product: {
      id: string;
      title: string;
      images: {
        id: string;
        public_id: string;
        secure_url: string;
      }[];
    };
    shop: {
      id: string;
      name: string;
    };
  }[];
}
